#gt915 touchpanel driver


obj-$(CONFIG_GOODIX_TS_TOUCHPANEL_DRIVER)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_GOODIX_TS_TOUCHPANEL_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GOODIX_TS_TOUCHPANEL_DEBUG)	+= goodix_tool.o
